export default [
  {
    id: 1,
    jobRole: "iOS Developer",
    company: "Apple",
    jobType: "Full Time",
    location: "Remote",
    experience: "Fresher",
    postedDate: "2024-03-01",
    skills: ["Swift", "Objective-C", "Xcode"],
    jobLink: "https://www.apple.com",
  },
  {
    id: 2,
    jobRole: "Backend Developer",
    company: "Google",
    jobType: "Part Time",
    location: "In-Office",
    experience: "Junior Level",
    postedDate: "2024-03-02",
    skills: ["Nodejs", "Express", "MongoDB"],
    jobLink: "https://www.google.com/",
  },
  {
    id: 3,
    jobRole: "Frontend Developer",
    company: "Amazon",
    jobType: "Intern",
    location: "Hybrid",
    experience: "Mid Level",
    postedDate: "2024-2-23",
    skills: ["React", "Vue", "Angular"],
    jobLink: "https://www.amazon.com/",
  },
  {
    id: 4,
    jobRole: "Android Developer",
    company: "Samsung",
    jobType: "Full Time",
    location: "Remote",
    experience: "Senior Level",
    postedDate: "2024-03-04",
    skills: ["Kotlin", "Java", "Android Studio"],
    jobLink: "https://www.samsung.com",
  },
  {
    id: 5,
    jobRole: "iOS Developer",
    company: "Apple",
    jobType: "Part Time",
    location: "In-Office",
    experience: "Fresher",
    postedDate: "2024-03-05",
    skills: ["Swift", "Objective-C", "Xcode"],
    jobLink: "https://www.apple.com",
  },
  {
    id: 6,
    jobRole: "Backend Developer",
    company: "Google",
    jobType: "Intern",
    location: "Hybrid",
    experience: "Junior Level",
    postedDate: "2024-03-06",
    skills: ["Nodejs", "Express", "MongoDB"],
    jobLink: "https://www.google.com/",
  },
  {
    id: 7,
    jobRole: "Frontend Developer",
    Company: "AppsFlyer",
    jobType: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    postedDate: "2024-02-27",
    skills: ["React", "Vue", "Angular"],
    jobLink: "https://www.appsflyer.com/",
  },
  {
    id: 8,
    jobRole: "Android Developer",
    company: "Geeksynergy",
    jobType: "Part Time",
    location: "In-Office",
    experience: "Senior Level",
    postedDate: "2024-03-08",
    skills: ["Kotlin", "Java", "Android Studio"],
    jobLink: "https://www.geeksynergy.com/",
  },
  {
    id: 9,
    jobRole: "iOS Developer",
    company: "Meta",
    jobType: "Intern",
    location: "Hybrid",
    experience: "Fresher",
    postedDate: "2024-03-09",
    skills: ["Swift", "Objective-C", "Xcode"],
    jobLink: "https://www.meta.com/",
  },
  {
    id: 10,
    jobRole: "Backend Developer",
    company: "Microsoft",
    jobType: "Full Time",
    location: "Remote",
    experience: "Junior Level",
    postedDate: "2024-03-10",
    skills: ["Nodejs", "Express", "MongoDB"],
    jobLink: "https://www.microsoft.com/en-us",
  },
  {
    id: 11,
    jobRole: "Frontend Developer",
    company: "Infosys",
    jobType: "Part Time",
    location: "In-Office",
    experience: "Mid Level",
    postedDate: "2024-03-11",
    skills: ["React", "Vue", "Angular"],
    jobLink: "https://www.infosys.com/",
  },
  {
    id: 12,
    jobRole: "Android Developer",
    company: "TCS",
    jobType: "Intern",
    location: "Hybrid",
    experience: "Senior Level",
    postedDate: "2024-03-12",
    skills: ["Kotlin", "Java", "Android Studio"],
    jobLink: "https://www.tcs.com/",
  },
  {
    id: 13,
    jobRole: "iOS Developer",
    company: "Wipro",
    jobType: "Full Time",
    location: "Remote",
    experience: "Fresher",
    postedDate: "2024-03-13",
    skills: ["Swift", "Objective-C", "Xcode"],
    jobLink: "https://www.wipro.com/",
  },
  {
    id: 14,
    jobRole: "Backend Developer",
    company: "HCL",
    jobType: "Part Time",
    location: "In-Office",
    experience: "Junior Level",
    postedDate: "2024-03-14",
    skills: ["Nodejs", "Express", "MongoDB"],
    jobLink: "https://www.hcltech.com/",
  },
  {
    id: 15,
    jobRole: "Frontend Developer",
    company: "Cognizant",
    jobType: "Intern",
    location: "Hybrid",
    experience: "Mid Level",
    postedDate: "2024-02-25",
    skills: ["React", "Vue", "Angular"],
    jobLink: "https://www.cognizant.com/",
  },
];
